### PR TITLE
Option for default loglevel

### PR DESCRIPTION
**Pull request by blt-r**
For terminal-based code editors it makes sense to not have any logging by default, so we need an option for that

### CODE REVIEW

**Comment by blt-r** [comment]
Also, #12 probably should be already closed, but after this it should be like definitely closed

**Comment by gasinvein** [comment]
Do you mind also fixing the new (unrelated) shellcheck error?

**Comment by blt-r** [comment]
Ok, now CI works

**Comment by gasinvein** [comment]
Thanks!

**Pull request merged**
